name: Giskard-CI-CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
    run-giskard-test-suite:
        name: Giskard-Test-Suite
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.9
              cache: 'pipenv'

          - name: Install dependencies
            run: |
              pip install --upgrade pip
              pip install pipenv

          - name: Cache pipenv
            id: cache
            uses: actions/cache@v2
            with:
              path: .
              key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          
          - name: Install dependencies
            working-directory: .
            if: steps.cache.outputs.cache-hit != 'true'
            run: pipenv install --system --deploy

          - name: Execute Giskard Test Suite
            run: python run_test_suite.py

          - name: comment on PR
            uses: mshick/add-pr-comment@v2
            with:
              message: |
                  TestSuite Results:
                  ${{ env.OUTPUT }}